version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: npm
    directory: "/packages/truss-wasm"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/packages/truss-url-signer"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/examples/vite-truss-wasm"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/examples/nextjs"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
