FROM rust:1-slim-bookworm AS builder

WORKDIR /build
COPY Cargo.toml Cargo.lock ./
COPY src/ src/

RUN cargo build --release --locked --features s3

FROM gcr.io/distroless/cc-debian12:nonroot

COPY --from=builder /build/target/release/truss /truss

EXPOSE 8080

ENTRYPOINT ["/truss", "serve"]
